### ISSUE TITLE
Error while parsing IDP-metadata

### ISSUE THREAD

**Issue by tvdijen** [OpenConext/OpenConext-engineblock#1239]
The current code assumes an SLO-endpoint to exist

```
Apr 26 11:28:43 sv1811042 EBLOG[1303]: [2023-04-26 11:28:43] app.ERROR: Trying to get property 'binding' of non-object [/apps/installation/OpenConext-engineblock/OpenConext-engineblock-6.9.0/src/OpenConext/EngineBlockBundle/Http/Respons
e/JsonHelper.php:55] {"session_id":null,"request_id":"6448eecb0b1a2"} {"exception":{"severity":"ERROR","location":"/apps/installation/OpenConext-engineblock/OpenConext-engineblock-6.9.0/library/EngineBlock/Application/ErrorHandler.php:8
3","userId":null,"idp":null,"sp":null,"details":"EngineBlock_Exception: Trying to get property 'binding' of non-object [/apps/installation/OpenConext-engineblock/OpenConext-engineblock-6.9.0/src/OpenConext/EngineBlockBundle/Http/Respons
e/JsonHelper.php:55]
#0 /apps/installation/OpenConext-engineblock/OpenConext-engineblock-6.9.0/src/OpenConext/EngineBlockBundle/Http/Response/JsonHelper.php(55): EngineBlock_Application_ErrorHandler->error()
#1 /apps/installation/OpenConext-engineblock/OpenConext-engineblock-6.9.0/src/OpenConext/EngineBlockBundle/Controller/Api/MetadataController.php(98): OpenConext\\EngineBlockBundle\\Http\\Response\\JsonHelper::serializeIdentityProvider()
#2 /apps/installation/OpenConext-engineblock/OpenConext-engineblock-6.9.0/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(151): OpenConext\\EngineBlockBundle\\Controller\\Api\\MetadataController->idpAction()
#3 /apps/installation/OpenConext-engineblock/OpenConext-engineblock-6.9.0/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(68): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw()
#4 /apps/installation/OpenConext-engineblock/OpenConext-engineblock-6.9.0/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(200): Symfony\\Component\\HttpKernel\\HttpKernel->handle()
#5 /apps/installation/OpenConext-engineblock/OpenConext-engineblock-6.9.0/web/app.php(17): Symfony\\Component\\HttpKernel\\Kernel->handle()\n#6 {main}","message_prefix":null}}
```

Culprit is `/apps/installation/OpenConext-engineblock/OpenConext-engineblock-6.9.0/src/OpenConext/EngineBlockBundle/Http/Response/JsonHelper.php:55`

**Comment by thijskh** [comment]
I think this is fixed in https://github.com/OpenConext/OpenConext-engineblock/pull/1229

**Comment by tvdijen** [comment]
@MKodde couldn't remember fixing it...  However, I don't see how removing equals fixing..

**Comment by thijskh** [comment]
It's completely unused. Unused code, especially when broken, can best be removed.
