### ISSUE TITLE
Metadata push returns 302 redirect on error instead of 400/500

### ISSUE THREAD

**Issue by baszoetekouw** [OpenConext/OpenConext-engineblock#1309]
This morning, we had issues with improper metadata updates being pushed to EB (on `/api/connections`).  This was caught correctly by EB (see exception below), but instead of returning a HTTP error to the caller (Manage), EB returned a redirect (HTTP 302).  

This is very unfortunate behaviour, because this caused Manage to think the update was successful and show a "metadata was pushed successfully" message to the user, which in turn caused lots of confusion.

Exception (redacted):
```
An exception occurred while executing ' INSERT INTO sso_provider_roles_eb5 (...)]:  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'xxxx' for key 'idx_sso_provider_roles_entity_id_type'
 | Caught Unhandled generic exception
{"session_id":null,"request_id":"66bdd0a5a1914"}
{"exception": {
    "severity":"ERROR",
    "location":"/opt/openconext/OpenConext-engineblock-6.10.0/src/OpenConext/EngineBlockBundle/EventListener/FallbackExceptionListener.php:83",
    "userId":null,
    "idp":null,
    "sp":null,
    "details":"EngineBlock_Exception:
An exception occurred while executing 'INSERT INTO sso_provider_roles_eb5 (...):

SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'sp-https://examencommissie.avans.nl' for key 'idx_sso_provider_roles_entity_id_type'
#0 /opt/openconext/OpenConext-engineblock-6.10.0/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php(214): OpenConext\\EngineBlockBundle\\EventListener\\FallbackExceptionListener->onKernelException(Object(Symfony\\Component\\HttpKernel\\Event\\GetResponseForExceptionEvent),
'kernel.exceptio...',
Object(Symfony\\Component\\EventDispatcher\\ContainerAwareEventDispatcher))
#1 /opt/openconext/OpenConext-engineblock-6.10.0/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php(44): Symfony\\Component\\EventDispatcher\\EventDispatcher->doDispatch(Array,
'kernel.exceptio...',
Object(Symfony\\Component\\HttpKernel\\Event\\GetResponseForExceptionEvent))
#2 /opt/openconext/OpenConext-engineblock-6.10.0/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(227): Symfony\\Component\\EventDispatcher\\EventDispatcher->dispatch('kernel.exceptio...',
Object(Symfony\\Component\\HttpKernel\\Event\\GetResponseForExceptionEvent))
#3 /opt/openconext/OpenConext-engineblock-6.10.0/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(79): Symfony\\Component\\HttpKernel\\HttpKernel->handleException(Object(Doctrine\\DBAL\\Exception\\UniqueConstraintViolationException),
Object(Symfony\\Component\\HttpFoundation\\Request),
1)
#4 /opt/openconext/OpenConext-engineblock-6.10.0/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(200): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request),
1,
true)
#5 /opt/openconext/OpenConext-engineblock-6.10.0/web/app.php(17): Symfony\\Component\\HttpKernel\\Kernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))
#6 {main}
```

**Comment by tvdijen** [comment]
I recently had an issue with json import/export between environments where a lot of the imported data got lost.. Could this be related?

**Comment by MKodde** [comment]
Thanks for the report @baszoetekouw 

And I'm happy to confirm I was able to reproduce this in my dev env. As demonstrated in the log snippet below.

```
engine:80 172.26.0.5 - manage [21/Aug/2024:09:23:48 +0000] "POST /api/connections HTTP/1.1" 302 955 "-" "IntelliJ HTTP Client/PhpStorm 2024.2"
engine:80 172.26.0.5 - - [21/Aug/2024:09:23:48 +0000] "GET /feedback/unknown-error HTTP/1.1" 500 3315 "-" "IntelliJ HTTP Client/PhpStorm 2024.2"
```

What is the expected behavior in `/api` requests? My gut tells me to respond with a

**Comment by thijskh** [comment]
This does not seem to be currently working in production (6.15.3) as a PUSH that generates an exception still returns HTTP 302.

The referenced commit a32f699248c0a4e45a2f5a0272f608fdee04be4f cannot be found on main (by me at least).

Recently this has been committed that seems related b7b3ba0898fb6d417628fad60aca6bde806d6ed2 (not yet released). So perhaps it's fixed in main afterall. But needs testing then.

**Comment by baszoetekouw** [comment]
This original fix was not lost, but rather it seems that EB can fail in multiple ways when importing metadata, and only one of these exceptions was fixed in this issue.

The other one that we encourtered yesterday was indeed already fixed by @pablothedude while fixing a different metadata import issue: https://github.com/OpenConext/OpenConext-engineblock/pull/1783

It seems that
