### ISSUE TITLE
Profile fails: Invalid values for attribute 'name', not an array: 'https://teams.test.surfconext.nl/shibboleth'

### ISSUE THREAD

**Issue by thijskh** [OpenConext/OpenConext-engineblock#139]
Logging into profile 4.4.1 on test fails with the following output:
![screenshot from 2015-03-31 13 52 58](https://cloud.githubusercontent.com/assets/3808792/6918499/7898cf48-d7af-11e4-8bec-62f138e594c9.png)

Logfile says:
```
Mar 31 13:52:30 t01 engineblock[12270]: EB[20e3ffd8ab77d00fca6de7ee20a0499e][551a8a7e10d16] [Message INFO] FLUSHING 24 LOG MESSAGES IN SESSION QUEUE (error caught)
Mar 31 13:52:30 t01 engineblock[12270]: > QUEUED TIMESTAMP: 2015-03-31T13:52:30+02:00| EB[20e3ffd8ab77d00fca6de7ee20a0499e][551a8a7dceb74] [Message ERR] Invalid values for attribute 'name', not an array: 'https://teams.test.surfconext.nl/shibboleth'
Mar 31 13:52:30 t01 engineblock[12270]: > QUEUED TIMESTAMP: 2015-03-31T13:52:30+02:00| EB[20e3ffd8ab77d00fca6de7ee20a0499e][551a8a7dceb74][DUMP 'REST Request' (1/6)] "GET \/simplesaml\/module.php\/janus\/services\/rest\/?method=arp&entityid=https%3A%2F%2Fserviceregistry.test.surfconext.nl%2Fsimplesaml%2Fmodule.php%2Fsaml%2Fsp%2Fmetadata.php%2Fdefault-sp&janus_key=engineblock&userid=engineblock&janus_sig=ffae6a920a7e72a9a7e8c84bd665247ef00fd3328637a5c1cb73d91fafd2085e0020eb1743ee9e06cfa061b5410316f452c5e5e9dffa43446ad75607ee71ff64&rest=1 HTTP\/1.1\r\nHost: serviceregistry.test.surfconext.nl\r\nConnection: close\r\nAccept-encoding: gzip, deflate\r\nUser-Agent: Zend_Http_Client\r\n\r\n"
Mar 31 13:52:30 t01 engineblock[12270]: > QUEUED TIMESTAMP: 2015-03-31T13:52:30+02:00| EB[20e3ffd8ab77d00fca6de7ee20a0499e][551a8a7dceb74][DUMP 'REST Response (original response below)' (2/6)] {}
Mar 31 13:52:30 t01 engineblock[12270]: > QUEUED TIMESTAMP: 2015-03-31T13:52:30+02:00| EB[20e3ffd8ab77d00fca6de7ee20a0499e][551a8a7dceb74][DUMP 'REST Request' (3/6)] "GET \/simplesaml\/module.php\/janus\/services\/rest\/?method=arp&entityid=https%3A%2F%2Fteams.test.surfconext.nl%2Fshibboleth&janus_key=engineblock&userid=engineblock&janus_sig=2c8a09f7b017847fabdf51b79ae5309a004b960639cb773456c5a657980eaa282fb1de14181e5e984209a03afefa374764e30094abf3029fe881197f4b3d64d1&rest=1 HTTP\/1.1\r\nHost: serviceregistry.test.surfconext.nl\r\nConnection: close\r\nAccept-encoding: gzip, deflate\r\nUser-Agent: Zend_Http_Client\r\n\r\n"
Mar 31 13:52:30 t01 engineblock[12270]: > QUEUED TIMESTAMP: 2015-03-31T13:52:30+02:00| EB[20e3ffd8ab77d00fca6de7ee20a0499e][551a8a7dceb74][DUMP 'REST Response (original response below)' (4/6)] {"name":"https:\/\/teams.test.surfconext.nl\/shibboleth","description":"ARP for entity https:\/\/teams.test.surfconext.nl\/shibboleth","attributes":{"urn:mace:dir:attribute-def:displayName":["*"],"urn:mace:dir:attribute-def:mail":["*"],"urn:mace:dir:attribute-def:uid":["*"]}}
Mar 31 13:52:30 t01 engineblock[12270]: > QUEUED TIMESTAMP: 2015-03-31T13:52:30+02:00| EB[20e3ffd8ab77d00fca6de7ee20a0499e][551a8a7dceb74][DUMP 'trace' (5/6)]!CHUNKSTART> "exception 'InvalidArgumentException' with message 'Invalid values for attribute 'name', not an array: 'https:\/\/teams.test.surfconext.nl\/shibboleth'' in \/opt\/data\/openconext\/OpenConext-engineblock-4.4.1\/vendor\/openconext\/engineblock-metadata\/src\/AttributeReleasePolicy.php:29\nStack trace:\n#0 \/opt\/data\/openconext\/OpenConext-engineblock-4.4.1\/application\/modules\/Profile\/Controller\/Index.php(41): OpenConext\\Component\\EngineBlockMetadata\\AttributeReleasePolicy->__construct(Array)\n#1 \/opt\/data\/openconext\/OpenConext-engineblock-4.4.1\/application\/modules\/Profile\/Controller\/Index.php(19): Profile_Controller_Index->_getSpAttributeList(Array)\n#2 [internal function]: Profile_Controller_Index->indexAction()\n#3 \/opt\/data\/openconext\/OpenConext-engineblock-4.4.1\/library\/EngineBlock\/Controller\/Abstract.php(43): call_user_func_array(Array, A
Mar 31 13:52:30 t01 engineblock[12270]: > QUEUED TIMESTAMP: 2015-03-31T13:52:30+02:00| EB[20e3ffd8ab77d00fca6de7ee20a0499e][551a8a7dceb74][DUMP 'trace' (5/6)]!CHUNK>rray)\n#4 \/opt\/data\/openconext\/OpenConext-engineblock-4.4.1\/library\/EngineBlock\/Dispatcher.php(67): EngineBlock_Controller_Abstract->handleAction('Index', Array)\n#5 \/opt\/data\/openconext\/OpenConext-engineblock-4.4.1\/library\/EngineBlock\/Dispatcher.php(43): EngineBlock_Dispatcher->_dispatch('\/')\n#6 \/opt\/data\/openconext\/OpenConext-engineblock-4.4.1\/www\/profile\/index.php(13): EngineBlock_Dispatcher->dispatch()\n#7 {main}\n\nNext exception 'EngineBlock_Exception' with message 'Invalid values for attribute 'name', not an array: 'https:\/\/teams.test.surfconext.nl\/shibboleth'' in \/opt\/data\/openconext\/OpenConext-engineblock-4.4.1\/library\/EngineBlock\/Dispatcher.php:79\nStack trace:\n#0 \/opt\/data\/openconext\/OpenConext-engineblock-4.4.1\/library\/EngineBlock\/Dispatcher.php(48): EngineBlock_Dispatcher->_handleDispatchException(Object(InvalidArgum
Mar 31 13:52:30 t01 engineblock[12270]: > QUEUED TIMESTAMP: 2015-03-31T13:52:30+02:00| EB[20e3ffd8ab77d00fca6de7ee20a0499e][551a8a7dceb74][DUMP 'trace' (5/6)]!CHUNKEND>entException))\n#1 \/opt\/data\/openconext\/OpenConext-engineblock-4.4.1\/www\/profile\/index.php(13): EngineBlock_Dispatcher->dispatch()\n#2 {main}"
Mar 31 13:52:30 t01 engineblock[12270]: > QUEUED TIMESTAMP: 2015-03-31T13:52:30+02:00| EB[20e3ffd8ab77d00fca6de7ee20a0499e][551a8a7dceb74][DUMP 'previous exception' (6/6)]!CHUNKSTART> "exception 'InvalidArgumentException' with message 'Invalid values for attribute 'name', not an array: 'https:\/\/teams.test.surfconext.nl\/shibboleth'' in \/opt\/data\/openconext\/OpenConext-engineblock-4.4.1\/vendor\/openconext\/engineblock-metadata\/src\/AttributeReleasePolicy.php:29\nStack trace:\n#0 \/opt\/data\/openconext\/OpenConext-engineblock-4.4.1\/application\/modules\/Profile\/Controller\/Index.php(41): OpenConext\\Component\\EngineBlockMetadata\\AttributeReleasePolicy->__construct(Array)\n#1 \/opt\/data\/openconext\/OpenConext-engineblock-4.4.1\/application\/modules\/Profile\/Controller\/Index.php(19): Profile_Controller_Index->_getSpAttributeList(Array)\n#2 [internal function]: Profile_Controller_Index->indexAction()\n#3 \/opt\/data\/openconext\/OpenConext-engineblock-4.4.1\/library\/EngineBlock\/Controller\/Abstract.php(43): call_user_func_a
Mar 31 13:52:30 t01 engineblock[12270]: > QUEUED TIMESTAMP: 2015-03-31T13:52:30+02:00| EB[20e3ffd8ab77d00fca6de7ee20a0499e][551a8a7dceb74][DUMP 'previous exception' (6/6)]!CHUNKEND>rray(Array, Array)\n#4 \/opt\/data\/openconext\/OpenConext-engineblock-4.4.1\/library\/EngineBlock\/Dispatcher.php(67): EngineBlock_Controller_Abstract->handleAction('Index', Array)\n#5 \/opt\/data\/openconext\/OpenConext-engineblock-4.4.1\/library\/EngineBlock\/Dispatcher.php(43): EngineBlock_Dispatcher->_dispatch('\/')\n#6 \/opt\/data\/openconext\/OpenConext-engineblock-4.4.1\/www\/profile\/index.php(13): EngineBlock_Dispatcher->dispatch()\n#7 {main}"
```

**Comment by relaxnow** [comment]
Sounds like an attribute manipulation gone wrong.
