### ISSUE TITLE
Array of value types and array of values have different size

### ISSUE THREAD

**Issue by phavekes** [OpenConext/OpenConext-engineblock#1468]
[This issue is imported from pivotal - Originaly created at Jun 7, 2018 by Thijs Kinkhorst](https://www.pivotaltracker.com/story/show/158184179)

Since EB 5.6.0 (saml2 3.1.0) EB throws a fatal exception "Array of value types and array of values have different size" in the following case:

1. Given an SP with an ARP with a filter for attribute A on specific attribute _values_,
1. and any Attribute Manipulation set (regardless of content).
1. A user logs in to that SP with multiple attribute values for attribute A
1. of which some, but not all are removed by the ARP filter.

An example of full stack trace is added in the comment.

The exception is thrown at https://github.com/simplesamlphp/saml2/commit/082f8fb779d1d8e71710e9bbac72f383cc3d0d9c#diff-35f750cac20c45bceb545dd2e20dae85R1576

Given a user with attribute values:
("aap", "noot", "mies") and an ARP value filter of "noot", when the exception is thrown, the variables are populated as follows:

valueTypes = 
array (
 0 => \'xs:string\',
 1 => \'xs:string\',
 2 => \'xs:string\',
)
values =
array (
 0 => \'noot\',
)

So the "types" are not "cleaned up" when the correponding values are removed.

Remarkably this happens only when an AM is run (but the AM itself can be anything or even dummy code).

A hotfix was to comment out the check for the exception. Because the behaviour is just fine in our case (there\'s a correponding type for the value, the other types are not used).

**Comment by phavekes** [comment]
```
Jun  7 10:20:12 papp3 EBLOG[19127]: [2018-06-07 10:20:12] engineblock.ERROR: Array of value types and array of values have different size for attribute \'urn:mace:dir:attribute-def:eduPersonEntitlement\' | Caught Unhandled generic exception {"session_id":",bm2k655MmmRuunqqhsuMIanBc4","request_id":"5b18eabc50162"} {"exception":{"severity":"ERROR","location":"/opt/openconext/OpenConext-engineblock-5.6.7/src/OpenConext/EngineBlockBundle/EventListener/FallbackExceptionListener.php:63","userId":null,"idp":null,"sp":null,"details":"EngineBlock_Exception: Array of value types and array of values have different size for attribute \'urn:mace:dir:attribute-def:eduPersonEntitlement\'
#0 [internal function]: OpenConext\\EngineBlockBundle\\EventListener\\FallbackExceptionListener->onKernelException(Object(Symfony\\Component\\HttpKernel\\Event\\GetResponseForExceptionEvent), \'kernel.exceptio...\', Object(Symfony\\Component\\EventDispatcher\\ContainerAwareEventDispatcher))
#1 /opt/openconext/OpenConext-engineblock-5.6.7/app/cache/prod/classes.php(2264): call_user_func(Array, Object(Symfony\\Component\\HttpKernel\\Event\\GetResponseForExceptionEvent), \'kernel.exceptio...\', Object(Symfony\\Component\\EventDispatcher\\ContainerAwareEventDispatcher))
#2 /opt/openconext/OpenConext-engineblock-5.6.7/app/cache/prod/classes.php(2179): Symfony\\Component\\EventDispatcher\\EventDispatcher->doDispatch(Array, \'kernel.exceptio...\', Object(Symfony\\Component\\HttpKernel\\Event\\GetResponseForExceptionEvent))
#3 /opt/openconext/OpenConext-engineblock-5.6.7/app/bootstrap.php.cache(3286): Symfony\\Component\\EventDispatcher\\EventDispatcher->dispatch(\'kernel.exceptio...\', Object(Symfony\\Component\\HttpKernel\\Event\\GetResponseForExceptionEvent))
#4 /opt/openconext/OpenConext-engineblock-5.6.7/app/bootstrap.php.cache(3222): Symfony\\Component\\HttpKernel\\HttpKernel->handleException(Object(Exception), Object(Symfony\\Component\\HttpFoundation\\Request), 1)
#5 /opt/openconext/OpenConext-engineblock-5.6.7/app/bootstrap.php.cache(3367): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#6 /opt/openconext/OpenConext-engineblock-5.6.7/app/bootstrap.php.cache(2566): Symfony\\Component\\HttpKernel\\DependencyInjection\\ContainerAwareHttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#7 /opt/openconext/OpenConext-engineblock-5.6.7/web/app.php(22): Symfony\\Component\\HttpKernel\\Kernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))
#8 {main}
Exception: Array of value types and array of values have different size for attribute \'urn:mace:dir:attribute-def:eduPersonEntitlement\'
#0 /opt/openconext/OpenConext-engineblock-5.6.7/vendor/simplesamlphp/saml2/src/SAML2/Assertion.php(1396): SAML2\\Assertion->addAttributeStatement(Object(DOMElement))
#1 /opt/openconext/OpenConext-engineblock-5.6.7/vendor/simplesamlphp/saml2/src/SAML2/Response.php(76): SAML2\\Assertion->toXML(Object(DOMElement))
#2 /opt/openconext/OpenConext-engineblock-5.6.7/library/EngineBlock/Corto/Module/Bindings.php(518): SAML2\\Response->toUnsignedXML()
#3 /opt/openconext/OpenConext-engineblock-5.6.7/library/EngineBlock/Corto/ProxyServer.php(719): EngineBlock_Corto_Module_Bindings->send(Object(EngineBlock_Saml2_ResponseAnnotationDecorator), Object(OpenConext\\Component\\EngineBlockMetadata\\Entity\\ServiceProvider))
#4 /opt/openconext/OpenConext-engineblock-5.6.7/library/EngineBlock/Corto/Module/Service/ProcessedAssertionConsumer.php(55): EngineBlock_Corto_ProxyServer->sendResponseToRequestIssuer(Object(EngineBlock_Saml2_AuthnRequestAnnotationDecorator), Object(EngineBlock_Saml2_ResponseAnnotationDecorator))
#5 /opt/openconext/OpenConext-engineblock-5.6.7/library/EngineBlock/Corto/Module/Services.php(54): EngineBlock_Corto_Module_Service_ProcessedAssertionConsumer->serve(\'processedAssert...\')
#6 /opt/openconext/OpenConext-engineblock-5.6.7/library/EngineBlock/Corto/Module/Bindings.php(625): EngineBlock_Corto_Module_Services->serve(\'processedAssert...\')
#7 /opt/openconext/OpenConext-engineblock-5.6.7/library/EngineBlock/Corto/Module/Bindings.php(492): EngineBlock_Corto_Module_Bindings->sendInternal(Object(EngineBlock_Saml2_ResponseAnnotationDecorator))
#8 /opt/openconext/OpenConext-engineblock-5.6.7/library/EngineBlock/Corto/Module/Service/ProvideConsent.php(100): EngineBlock_Corto_Module_Bindings->send(Object(EngineBlock_Saml2_ResponseAnnotationDecorator), Object(OpenConext\\Component\\EngineBlockMetadata\\Entity\\ServiceProvider))
#9 /opt/openconext/OpenConext-engineblock-5.6.7/library/EngineBlock/Corto/Module/Services.php(54): EngineBlock_Corto_Module_Service_ProvideConsent->serve(\'provideConsentS...\')
#10 /opt/openconext/OpenConext-engineblock-5.6.7/library/EngineBlock/Corto/Module/Bindings.php(625): EngineBlock_Corto_Module_Services->serve(\'provideConsentS...\')
#11 /opt/openconext/OpenConext-engineblock-5.6.7/library/EngineBlock/Corto/Module/Bindings.php(492): EngineBlock_Corto_Module_Bindings->sendInternal(Object(EngineBlock_Saml2_ResponseAnnotationDecorator))
#12 /opt/openconext/OpenConext-engineblock-5.6.7/library/EngineBlock/Corto/Module/Service/AssertionConsumer.php(117): EngineBlock_Corto_Module_Bindings->send(Object(EngineBlock_Saml2_ResponseAnnotationDecorator), Object(OpenConext\\Component\\EngineBlockMetadata\\Entity\\ServiceProvider))
#13 /opt/openconext/OpenConext-engineblock-5.6.7/library/EngineBlock/Corto/Module/Services.php(54): EngineBlock_Corto_Module_Service_AssertionConsumer->serve(\'assertionConsum...\')
#14 /opt/openconext/OpenConext-engineblock-5.6.7/library/EngineBlock/Corto/ProxyServer.php(332): EngineBlock_Corto_Module_Services->serve(\'assertionConsum...\')
#15 /opt/openconext/OpenConext-engineblock-5.6.7/library/EngineBlock/Corto/Adapter.php(308): EngineBlock_Corto_ProxyServer->serve(\'assertionConsum...\', \'\')
#16 /opt/openconext/OpenConext-engineblock-5.6.7/library/EngineBlock/Corto/Adapter.php(92): EngineBlock_Corto_Adapter->_callCortoServiceUri(\'assertionConsum...\')
#17 /opt/openconext/OpenConext-engineblock-5.6.7/src/OpenConext/EngineBlockBundle/Controller/ServiceProviderController.php(64): EngineBlock_Corto_Adapter->consumeAssertion()
#18 [internal function]: OpenConext\\EngineBlockBundle\\Controller\\ServiceProviderController->consumeAssertionAction()
#19 /opt/openconext/OpenConext-engineblock-5.6.7/app/bootstrap.php.cache(3254): call_user_func_array(Array, Array)
#20 /opt/openconext/OpenConext-engineblock-5.6.7/app/bootstrap.php.cache(3213): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 1)
#21 /opt/openconext/OpenConext-engineblock-5.6.7/app/bootstrap.php.cache(3367): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#22 /opt/openconext/OpenConext-engineblock-5.6.7/app/bootstrap.php.cache(2566): Symfony\\Component\\HttpKernel\\DependencyInjection\\ContainerAwareHttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#23 /opt/openconext/OpenConext-engineblock-5.6.7/web/app.php(22): Symfony\\Component\\HttpKernel\\Kernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))
#24 {main}","message_prefix":null},"previous_exceptions":["exception \'Exception\' with message \'Array of value types and array of values have different size for attribute \'urn:mace:dir:attribute-def:eduPersonEntitlement\'\' in /opt/openconext/OpenConext-engineblock-5.6.7/vendor/simplesamlphp/saml2/src/SAML2/Assertion.php:1579
Stack trace:
#0 /opt/openconext/OpenConext-engineblock-5.6.7/vendor/simplesamlphp/saml2/src/SAML2/Assertion.php(1396): SAML2\\Assertion->addAttributeStatement(Object(DOMElement))
#1 /opt/openconext/OpenConext-engineblock-5.6.7/vendor/simplesamlphp/saml2/src/SAML2/Response.php(76): SAML2\\Assertion->toXML(Object(DOMElement))
#2 /opt/openconext/OpenConext-engineblock-5.6.7/library/EngineBlock/Corto/Module/Bindings.php(518): SAML2\\Response->toUnsignedXML()
#3 /opt/openconext/OpenConext-engineblock-5.6.7/library/EngineBlock/Corto/ProxyServer.php(719): EngineBlock_Corto_Module_Bindings->send(Object(EngineBlock_Saml2_ResponseAnnotationDecorator), Object(OpenConext\\Component\\EngineBlockMetadata\\Entity\\ServiceProvider))
#4 /opt/openconext/OpenConext-engineblock-5.6.7/library/EngineBlock/Corto/Module/Service/ProcessedAssertionConsumer.php(55): EngineBlock_Corto_ProxyServer->sendResponseToRequestIssuer(Object(EngineBlock_Saml2_AuthnRequestAnnotationDecorator), Object(EngineBlock_Saml2_ResponseAnnotationDecorator))
#5 /opt/openconext/OpenConext-engineblock-5.6.7/library/EngineBlock/Corto/Module/Services.php(54): EngineBlock_Corto_Module_Service_ProcessedAssertionConsumer->serve(\'processedAssert...\')
#6 /opt/openconext/OpenConext-engineblock-5.6.7/library/EngineBlock/Corto/Module/Bindings.php(625): EngineBlock_Corto_Module_Services->serve(\'processedAssert...\')
#7 /opt/openconext/OpenConext-engineblock-5.6.7/library/EngineBlock/Corto/Module/Bindings.php(492): EngineBlock_Corto_Module_Bindings->sendInternal(Object(EngineBlock_Saml2_ResponseAnnotationDecorator))
#8 /opt/openconext/OpenConext-engineblock-5.6.7/library/EngineBlock/Corto/Module/Service/ProvideConsent.php(100): EngineBlock_Corto_Module_Bindings->send(Object(EngineBlock_Saml2_ResponseAnnotationDecorator), Object(OpenConext\\Component\\EngineBlockMetadata\\Entity\\ServiceProvider))
#9 /opt/openconext/OpenConext-engineblock-5.6.7/library/EngineBlock/Corto/Module/Services.php(54): EngineBlock_Corto_Module_Service_ProvideConsent->serve(\'provideConsentS...\')
#10 /opt/openconext/OpenConext-engineblock-5.6.7/library/EngineBlock/Corto/Module/Bindings.php(625): EngineBlock_Corto_Module_Services->serve(\'provideConsentS...\')
#11 /opt/openconext/OpenConext-engineblock-5.6.7/library/EngineBlock/Corto/Module/Bindings.php(492): EngineBlock_Corto_Module_Bindings->sendInternal(Object(EngineBlock_Saml2_ResponseAnnotationDecorator))
#12 /opt/openconext/OpenConext-engineblock-5.6.7/library/EngineBlock/Corto/Module/Service/AssertionConsumer.php(117): EngineBlock_Corto_Module_Bindings->send(Object(EngineBlock_Saml2_ResponseAnnotationDecorator), Object(OpenConext\\Component\\EngineBlockMetadata\\Entity\\ServiceProvider))
#13 /opt/openconext/OpenConext-engineblock-5.6.7/library/EngineBlock/Corto/Module/Services.php(54): EngineBlock_Corto_Module_Service_AssertionConsumer->serve(\'assertionConsum...\')
#14 /opt/openconext/OpenConext-engineblock-5.6.7/library/EngineBlock/Corto/ProxyServer.php(332): EngineBlock_Corto_Module_Services->serve(\'assertionConsum...\')
#15 /opt/openconext/OpenConext-engineblock-5.6.7/library/EngineBlock/Corto/Adapter.php(308): EngineBlock_Corto_ProxyServer->serve(\'assertionConsum...\', \'\')
#16 /opt/openconext/OpenConext-engineblock-5.6.7/library/EngineBlock/Corto/Adapter.php(92): EngineBlock_Corto_Adapter->_callCortoServiceUri(\'assertionConsum...\')
#17 /opt/openconext/OpenConext-engineblock-5.6.7/src/OpenConext/EngineBlockBundle/Controller/ServiceProviderController.php(64): EngineBlock_Corto_Adapter->consumeAssertion()
#18 [internal function]: OpenConext\\EngineBlockBundle\\Controller\\ServiceProviderController->consumeAssertionAction()
#19 /opt/openconext/OpenConext-engineblock-5.6.7/app/bootstrap.php.cache(3254): call_user_func_array(Array, Array)
#20 /opt/openconext/OpenConext-engineblock-5.6.7/app/bootstrap.php.cache(3213): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 1)
#21 /opt/openconext/OpenConext-engineblock-5.6.7/app/bootstrap.php.cache(3367): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#22 /opt/openconext/OpenConext-engineblock-5.6.7/app/bootstrap.php.cache(2566): Symfony\\Component\\HttpKernel\\DependencyInjection\\ContainerAwareHttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#23 /opt/openconext/OpenConext-engineblock-5.6.7/web/app.php(22): Symfony\\Component\\HttpKernel\\Kernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))
#24 {main}"]}

``` (Thijs Kinkhorst - Jun 7, 2018)

**Comment by phavekes** [comment]
After some tinkering I\'ve been able to reproduce the problem in a behat scenario. The existence of the xs:type attribute on a saml:attributevalue element seems to trigger the error.

`Array of value types and array of values have different size for attribute` is thrown
```
            <saml:Attribute Name="rhyme">
                <saml:AttributeValue xsi:type="xs:string">aap</saml:AttributeValue>
                <saml:AttributeValue xsi:type="xs:string">noot</saml:AttributeValue>
                <saml:AttributeValue xsi:type="xs:string">mies</saml:AttributeValue>
            </saml:Attribute>
```

No problems when the attribute is defined without xsi:type
```
            <saml:Attribute Name="rhyme">
                <saml:AttributeValue>aap</saml:AttributeValue>
                <saml:AttributeValue>noot</saml:AttributeValue>
                <saml:AttributeValue>mies</saml:AttributeValue>
            </saml:Attribute>
```

@thijskh do IdP\'s typically use the xsi:type definition on the attribute values? In other words, should we also configure our behat mock IdP to use them? (Michiel Kodde - Jun 13, 2018)

**Comment by phavekes** [comment]
I checked and both with and without are common, about half/half.

Could you confirm that an AM needs to be present to trigger the behaviour? (Thijs Kinkhorst - Jun 13, 2018)

**Comment by phavekes** [comment]
In my current tests I need AM and ARP to get the exception. I will verify this in more detail tomorrow.  (Michiel Kodde - Jun 14, 2018)

**Comment by phavekes** [comment]
The described problem is gone but a new one has surfaced. The consent screen now no longer shows the value for an attribute affected by this case.

Given a user that has 3 affiliations (student, faculty, employee), the SP only has faculty as allowed value in the ARP.

In 5.7.1 the consentscreen correctly shows "faculty".
In 5.7.2 the consentscreen shows the faculty attribute but with empty value.

Note that the correct attribute content is passed to the SP nonetheless (it receives just faculty) so it seems that specifically the consent screen is off since this change.
 (Thijs Kinkhorst - Jun 26, 2018)

**Comment by phavekes** [comment]
The problem was caused in the twig template. See before and after screenshots (also with a sneak peek into the bugfix).
 (Michiel Kodde - Jun 27, 2018)
