### ISSUE TITLE
Make time sync error a user visible error

### ISSUE THREAD

**Issue by phavekes** [OpenConext/OpenConext-engineblock#1534]
[This issue is imported from pivotal - Originaly created at Feb 19, 2019 by Thijs Kinkhorst](https://www.pivotaltracker.com/story/show/164076668)

When the received assertion is not valid, EB logs

```
Caught Exception "EngineBlock_Corto_Module_Bindings_VerificationException":"Received an assertion that has expired. Check clock synchronization on IdP and SP.", redirecting to route "authentication_feedback_verification_failed"
```

The exception description is very useful because this is a common error. However, EB only presents the abstract error "Invalid Identity Provider Response" (related to the VerificationException). It would be helpful if EB could be explicit to the user that it rejects the assertion due to a clock issue.

This will help IdPs that have this problem to quickly identify and fix it rather than to first email us with the question why they get "error - an error occurred".

**Comment by phavekes** [comment]
We assume, our time is correct. If this is not the case, the IdP will mention this to us. (Michiel Kodde - Feb 26, 2019)

**Comment by phavekes** [comment]
As I mentioned (and spammed you with) in the GitHub PR, @bstrooband mentioned the session time validation violation which might occur when the assertion is validated in Engines ACS. This would yield a similar error message which is described in the story description. But it would read:

`Received an assertion with a session that has expired. Check clock synchronization on IdP and SP.`

Is this error message a common occurence? Or even if it is not, must we add a custom error response for it?

@bartgeesink @thijskh @pmeulen  (Michiel Kodde - Apr 1, 2019)

**Comment by phavekes** [comment]
We\'ve seen maximum of about 20 `Response processing failed: Invalid Assertion in SAML Response, erorrs: "Received an assertion that has expired. Check clock synchronization on IdP and SP.", "Received an assertion with a session that has expired. Check clock synchronization on IdP and SP." | -> Redirecting to feedback page` messages per day in the last 30 days, compared to a maximum of about 500 for `Received an assertion that has expired. Check clock synchronization on IdP and SP`

```
exception \'SAML2\Assertion\Exception\InvalidAssertionException\' with message \'Invalid Assertion in SAML Response, erorrs: "Received an assertion that has expired. Check clock synchronization on IdP and SP.", "Received an assertion with a session that has expired. Check clock synchronization on IdP and SP."\' in /opt/openconext/OpenConext-engineblock-5.8.7/vendor/simplesamlphp/saml2/src/SAML2/Assertion/Processor.php:145
Stack trace:
#0 /opt/openconext/OpenConext-engineblock-5.8.7/vendor/simplesamlphp/saml2/src/SAML2/Assertion/Processor.php(113): SAML2\Assertion\Processor->validateAssertion(Object(SAML2\Assertion))
#1 /opt/openconext/OpenConext-engineblock-5.8.7/vendor/simplesamlphp/saml2/src/SAML2/Assertion/Processor.php(85): SAML2\Assertion\Processor->process(Object(SAML2\Assertion))
#2 /opt/openconext/OpenConext-engineblock-5.8.7/vendor/simplesamlphp/saml2/src/SAML2/Response/Processor.php(157): SAML2\Assertion\Processor->processAssertions(Array)
#3 /opt/openconext/OpenConext-engineblock-5.8.7/vendor/simplesamlphp/saml2/src/SAML2/Response/Processor.php(88): SAML2\Response\Processor->processAssertions(Object(SAML2\Response))
#4 /opt/openconext/OpenConext-engineblock-5.8.7/library/EngineBlock/Corto/Module/Bindings.php(361): SAML2\Response\Processor->process(Object(SAML2\Configuration\ServiceProvider), Object(SAML2\Configuration\IdentityProvider), Object(SAML2\Configuration\Destination), Object(SAML2\Response))
#5 /opt/openconext/OpenConext-engineblock-5.8.7/library/EngineBlock/Corto/Module/Service/AssertionConsumer.php(41): EngineBlock_Corto_Module_Bindings->receiveResponse()
#6 /opt/openconext/OpenConext-engineblock-5.8.7/library/EngineBlock/Corto/Module/Services.php(54): EngineBlock_Corto_Module_Service_AssertionConsumer->serve(\'assertionConsum...\')
#7 /opt/openconext/OpenConext-engineblock-5.8.7/library/EngineBlock/Corto/ProxyServer.php(339): EngineBlock_Corto_Module_Services->serve(\'assertionConsum...\')
#8 /opt/openconext/OpenConext-engineblock-5.8.7/library/EngineBlock/Corto/Adapter.php(313): EngineBlock_Corto_ProxyServer->serve(\'assertionConsum...\', \'\')
#9 /opt/openconext/OpenConext-engineblock-5.8.7/library/EngineBlock/Corto/Adapter.php(86): EngineBlock_Corto_Adapter->_callCortoServiceUri(\'assertionConsum...\')
#10 /opt/openconext/OpenConext-engineblock-5.8.7/src/OpenConext/EngineBlockBundle/Controller/ServiceProviderController.php(52): EngineBlock_Corto_Adapter->consumeAssertion()
#11 [internal function]: OpenConext\EngineBlockBundle\Controller\ServiceProviderController->consumeAssertionAction()
#12 /opt/openconext/OpenConext-engineblock-5.8.7/app/bootstrap.php.cache(3263): call_user_func_array(Array, Array)
#13 /opt/openconext/OpenConext-engineblock-5.8.7/app/bootstrap.php.cache(3222): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#14 /opt/openconext/OpenConext-engineblock-5.8.7/app/bootstrap.php.cache(3376): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#15 /opt/openconext/OpenConext-engineblock-5.8.7/app/bootstrap.php.cache(2575): Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#16 /opt/openconext/OpenConext-engineblock-5.8.7/web/app.php(22): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#17 {main}
``` (Pieter van der Meulen - Apr 1, 2019)

**Comment by phavekes** [comment]
Does a Assertion that is not yet valid lead to the same error as an Assertion that has expired? (Pieter van der Meulen - Apr 1, 2019)

**Comment by phavekes** [comment]
Suggestion for messages:
EN: "The Assertion is not yet valid or has expired, please verify that the time on the IdP is correct"
NL: "De Assertion is nog niet geldig of is verlopen, controleer de tijd op de IdP"

I\'ve chosen not speak about "time synchronisation" between EB and the IdP, but to "blame" the IdP as this is typically where the problem lies. (Pieter van der Meulen - Apr 1, 2019)

**Comment by phavekes** [comment]
Thanks for the message suggestions! Feedback to the other responses:

1.  Quote: `We\'ve seen maximum of about 20 ... compared to a maximum of about 500 for  Received an assertion that has expired.`
Question: Even though the error occures much more infrequent, we can still easily catch and handle it in this PR. So if you like me to add it in scope, I\'m more than willing.
2. Quote: `Does a Assertion that is not yet valid lead to the same error as an Assertion that has expired?`
Answer: Yes, for now the same error page is rendered for both situations. Again, it\'s easy to render different texts for each different timing situation. (Michiel Kodde - Apr 1, 2019)

**Comment by phavekes** [comment]
@michielkodde: 

#1: I wonder whether an expired authn session as well is due to a clock issue at the IdP, or whether it is due to another problem. So I\'m not sure what the error message should be.
#2: I\'d say use the same error. The goal is to make the IdP verify their clock, whether is fast or slow is not that relevant. (Pieter van der Meulen - Apr 1, 2019)

**Comment by phavekes** [comment]
@pmeulen this is what I ended up with. I split your proposed sentence in half. Using the first part as the title, and the latter for the error text.  (Michiel Kodde - Apr 1, 2019)
