### ISSUE TITLE
edugain metadata broken: Unrecognized field: publishableInEdugain

### ISSUE THREAD

**Issue by thijskh** [OpenConext/OpenConext-engineblock#159]
Since EB 4.4, EB's eduGAIN metadata as linked from the engine front page yields an error:

```
Jun 22 16:45:29 t01 EBLOG[20391]: > QUEUED TIMESTAMP: 2015-06-22T16:45:29+02:00| EB[j3F6m9l9mO-YYfDal7VX5iIjbX2][55881f8811327] [Message ERR] Unrecognized field: publishableInEdugain
Jun 22 16:45:29 t01 EBLOG[20391]: > QUEUED TIMESTAMP: 2015-06-22T16:45:29+02:00| EB[j3F6m9l9mO-YYfDal7VX5iIjbX2][55881f8811327][DUMP 'trace' (1/2)]!CHUNKSTART> "exception 'Doctrine\\ORM\\ORMExce
ption' with message 'Unrecognized field: publishableInEdugain' in \/opt\/data\/openconext\/OpenConext-engineblock-4.4.2\/vendor\/doctrine\/orm\/lib\/Doctrine\/ORM\/ORMException.php:100\nStack tr
ace:\n#0 \/opt\/data\/openconext\/OpenConext-engineblock-4.4.2\/vendor\/doctrine\/orm\/lib\/Doctrine\/ORM\/Persisters\/BasicEntityPersister.php(1686): Doctrine\\ORM\\ORMException::unrecognizedFi
eld('publishableInEd...')\n#1 \/opt\/data\/openconext\/OpenConext-engineblock-4.4.2\/vendor\/doctrine\/orm\/lib\/Doctrine\/ORM\/Persisters\/BasicEntityPersister.php(1615): Doctrine\\ORM\\Persist
ers\\BasicEntityPersister->getSelectConditionStatementColumnSQL('publishableInEd...', NULL)\n#2 \/opt\/data\/openconext\/OpenConext-engineblock-4.4.2\/vendor\/doctrine\/orm\/lib\/Doctrine\/ORM\/
Persisters\/BasicEntityPersister.php(1706): Doctrine\\ORM\\Persisters\\Basic
Jun 22 16:45:29 t01 EBLOG[20391]: > QUEUED TIMESTAMP: 2015-06-22T16:45:29+02:00| EB[j3F6m9l9mO-YYfDal7VX5iIjbX2][55881f8811327][DUMP 'trace' (1/2)]!CHUNK>EntityPersister->getSelectConditionState
mentSQL('publishableInEd...', true, NULL)\n#3 \/opt\/data\/openconext\/OpenConext-engineblock-4.4.2\/vendor\/doctrine\/orm\/lib\/Doctrine\/ORM\/Persisters\/SingleTablePersister.php(127): Doctrin
e\\ORM\\Persisters\\BasicEntityPersister->getSelectConditionSQL(Array, NULL)\n#4 \/opt\/data\/openconext\/OpenConext-engineblock-4.4.2\/vendor\/doctrine\/orm\/lib\/Doctrine\/ORM\/Persisters\/Bas
icEntityPersister.php(1115): Doctrine\\ORM\\Persisters\\SingleTablePersister->getSelectConditionSQL(Array, NULL)\n#5 \/opt\/data\/openconext\/OpenConext-engineblock-4.4.2\/vendor\/doctrine\/orm\
/lib\/Doctrine\/ORM\/Persisters\/BasicEntityPersister.php(928): Doctrine\\ORM\\Persisters\\BasicEntityPersister->getSelectSQL(Array, NULL, 0, NULL, NULL, NULL)\n#6 \/opt\/data\/openconext\/OpenC
onext-engineblock-4.4.2\/vendor\/doctrine\/orm\/lib\/Doctrine\/ORM\/Ent
Jun 22 16:45:29 t01 EBLOG[20391]: > QUEUED TIMESTAMP: 2015-06-22T16:45:29+02:00| EB[j3F6m9l9mO-YYfDal7VX5iIjbX2][55881f8811327][DUMP 'trace' (1/2)]!CHUNK>ityRepository.php(181): Doctrine\\ORM\\P
ersisters\\BasicEntityPersister->loadAll(Array, NULL, NULL, NULL)\n#7 \/opt\/data\/openconext\/OpenConext-engineblock-4.4.2\/vendor\/openconext\/engineblock-metadata\/src\/MetadataRepository\/Do
ctrineMetadataRepository.php(215): Doctrine\\ORM\\EntityRepository->findBy(Array)\n#8 \/opt\/data\/openconext\/OpenConext-engineblock-4.4.2\/vendor\/openconext\/engineblock-metadata\/src\/Metada
taRepository\/CompositeMetadataRepository.php(236): OpenConext\\Component\\EngineBlockMetadata\\MetadataRepository\\DoctrineMetadataRepository->findEntitiesPublishableInEdugain()\n#9 \/opt\/data
\/openconext\/OpenConext-engineblock-4.4.2\/library\/EngineBlock\/Corto\/Module\/Service\/EdugainMetadata.php(20): OpenConext\\Component\\EngineBlockMetadata\\MetadataRepository\\CompositeMetada
taRepository->findEntitiesPublishableInEdugain()\n#10 \/opt\/data\/open
Jun 22 16:45:29 t01 EBLOG[20391]: > QUEUED TIMESTAMP: 2015-06-22T16:45:29+02:00| EB[j3F6m9l9mO-YYfDal7VX5iIjbX2][55881f8811327][DUMP 'trace' (1/2)]!CHUNK>conext\/OpenConext-engineblock-4.4.2\/li
brary\/EngineBlock\/Corto\/Module\/Services.php(56): EngineBlock_Corto_Module_Service_EdugainMetadata->serve('edugainMetadata...')\n#11 \/opt\/data\/openconext\/OpenConext-engineblock-4.4.2\/lib
rary\/EngineBlock\/Corto\/ProxyServer.php(326): EngineBlock_Corto_Module_Services->serve('edugainMetadata...')\n#12 \/opt\/data\/openconext\/OpenConext-engineblock-4.4.2\/library\/EngineBlock\/C
orto\/Adapter.php(322): EngineBlock_Corto_ProxyServer->serve('edugainMetadata...', '')\n#13 \/opt\/data\/openconext\/OpenConext-engineblock-4.4.2\/library\/EngineBlock\/Corto\/Adapter.php(95): E
ngineBlock_Corto_Adapter->_callCortoServiceUri('edugainMetadata...')\n#14 \/opt\/data\/openconext\/OpenConext-engineblock-4.4.2\/application\/modules\/Authentication\/Controller\/Proxy.php(67): 
EngineBlock_Corto_Adapter->edugainMetadata('')\n#15 [internal function]
Jun 22 16:45:29 t01 EBLOG[20391]: > QUEUED TIMESTAMP: 2015-06-22T16:45:29+02:00| EB[j3F6m9l9mO-YYfDal7VX5iIjbX2][55881f8811327][DUMP 'trace' (1/2)]!CHUNK>: Authentication_Controller_Proxy->eduga
inMetaDataAction()\n#16 \/opt\/data\/openconext\/OpenConext-engineblock-4.4.2\/library\/EngineBlock\/Controller\/Abstract.php(43): call_user_func_array(Array, Array)\n#17 \/opt\/data\/openconext
\/OpenConext-engineblock-4.4.2\/library\/EngineBlock\/Dispatcher.php(67): EngineBlock_Controller_Abstract->handleAction('EdugainMetadata', Array)\n#18 \/opt\/data\/openconext\/OpenConext-engineb
lock-4.4.2\/library\/EngineBlock\/Dispatcher.php(43): EngineBlock_Dispatcher->_dispatch('\/authentication...')\n#19 \/opt\/data\/openconext\/OpenConext-engineblock-4.4.2\/www\/authentication\/in
dex.php(13): EngineBlock_Dispatcher->dispatch()\n#20 {main}\n\nNext exception 'EngineBlock_Exception' with message 'Unrecognized field: publishableInEdugain' in \/opt\/data\/openconext\/OpenCone
xt-engineblock-4.4.2\/library\/EngineBlock\/Dispatcher.php:79\nStack tr
```

**Comment by relaxnow** [comment]
Fixed with https://github.com/OpenConext/OpenConext-engineblock-metadata/commit/4ebd162e6a68c572e1dc6d74038b38bee4aef3df and https://github.com/OpenConext/OpenConext-engineblock/commit/1e1ddd1a4ae6643d738e54be320b8e042d2abb0d and
