### ISSUE TITLE
The mdui::Logo can be empty, causing issues in the application when accessed

### ISSUE THREAD

**Issue by phavekes** [OpenConext/OpenConext-engineblock#1725]
[This issue is imported from pivotal - Originaly created at Jul 5, 2023 by Michiel Kodde](https://www.pivotaltracker.com/story/show/185540656)

### Tim and Arnout found some issues regarding this issue:

```
Nog een aanvulling;  we zien ook dit:
Uncaught Doctrine\DBAL\DBALException: Unknown column type "engineblock_metadata_mdui" requested
Terwijl we wel een database-migratie hebben uitgevoerd en ook een mdui-column in de database zien
```

When logo is empty, this code section accesses a null instead of a logo, causing an error
`https://github.com/OpenConext/OpenConext-engineblock/blob/master/library/EngineBlock/Corto/Filter/Command/EnforcePolicy.php#L62`

### Provided Stack trace:
```
Jun 29 12:07:36 sv1811042 EBLOG[31035]: PHP Notice:  Undefined index: width in /apps/installation/OpenConext-engineblock/OpenConext-engineblock-6.11.0/src/OpenConext/EngineBlock/Metadata/Logo.php on line 45
Jun 29 12:07:36 sv1811042 EBLOG[31035]: [2023-06-29 12:07:36] app.ERROR: Undefined index: width [/apps/installation/OpenConext-engineblock/OpenConext-engineblock-6.11.0/src/OpenConext/EngineBlock/Metadata/Logo.php:45] {"session_id":"ebf10h78am74g2161t0dtp9qec","request_id":"649d57e8469f4"} {"exception":{"severity":"ERROR","location":"/apps/installation/OpenConext-engineblock/OpenConext-engineblock-6.11.0/library/EngineBlock/Application/ErrorHandler.php:83","userId":null,"idp":null,"sp":null,"details":"EngineBlock_Exception: Undefined index: width [/apps/installation/OpenConext-engineblock/OpenConext-engineblock-6.11.0/src/OpenConext/EngineBlock/Metadata/Logo.php:45]\n#0 /apps/installation/OpenConext-engineblock/OpenConext-engineblock-6.11.0/src/OpenConext/EngineBlock/Metadata/Logo.php(45): EngineBlock_Application_ErrorHandler->error()\n#1 /apps/installation/OpenConext-engineblock/OpenConext-engineblock-6.11.0/src/OpenConext/EngineBlock/Metadata/Mdui.php(130): OpenConext\\EngineBlock\\Metadata\\Logo::fromJson()\n#2 /apps/installation/OpenConext-engineblock/OpenConext-engineblock-6.11.0/src/OpenConext/EngineBlockBundle/Doctrine/Type/MetadataMduiType.php(62): OpenConext\\EngineBlock\\Metadata\\Mdui::fromJson()\n#3 /apps/installation/OpenConext-engineblock/OpenConext-engineblock-6.11.0/vendor/doctrine/orm/lib/Doctrine/ORM/Internal/Hydration/AbstractHydrator.php(316): OpenConext\\EngineBlockBundle\\Doctrine\\Type\\MetadataMduiType->convertToPHPValue()\n#4 /apps/installation/OpenConext-engineblock/OpenConext-engineblock-6.11.0/vendor/doctrine/orm/lib/Doctrine/ORM/Internal/Hydration/ObjectHydrator.php(331): Doctrine\\ORM\\Internal\\Hydration\\AbstractHydrator->gatherRowData()\n#5 /apps/installation/OpenConext-engineblock/OpenConext-engineblock-6.11.0/vendor/doctrine/orm/lib/Doctrine/ORM/Internal/Hydration/ObjectHydrator.php(162): Doctrine\\ORM\\Internal\\Hydration\\ObjectHydrator->hydrateRowData()\n#6 /apps/installation/OpenConext-engineblock/OpenConext-engineblock-6.11.0/vendor/doctrine/orm/lib/Doctrine/ORM/Internal/Hydration/AbstractHydrator.php(153): Doctrine\\ORM\\Internal\\Hydration\\ObjectHydrator->hydrateAllData()\n#7 /apps/installation/OpenConext-engineblock/OpenConext-engineblock-6.11.0/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(1001): Doctrine\\ORM\\Internal\\Hydration\\AbstractHydrator->hydrateAll()\n#8 /apps/installation/OpenConext-engineblock/OpenConext-engineblock-6.11.0/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(947): Doctrine\\ORM\\AbstractQuery->executeIgnoreQueryCache()\n#9 /apps/installation/OpenConext-engineblock/OpenConext-engineblock-6.11.0/src/OpenConext/EngineBlock/Metadata/MetadataRepository/DoctrineMetadataRepository.php(150): Doctrine\\ORM\\AbstractQuery->execute()\n#10 [internal function]: OpenConext\\EngineBlock\\Metadata\\MetadataRepository\\DoctrineMetadataRepository->findIdentityProviderByEntityId()\n#11 /apps/installation/OpenConext-engineblock/OpenConext-engineblock-6.11.0/src/OpenConext/EngineBlock/Metadata/MetadataRepository/CachedDoctrineMetadataRepository.php(73): call_user_func_array()\n#12 /apps/installation/OpenConext-engineblock/OpenConext-engineblock-6.11.0/src/OpenConext/EngineBlock/Metadata/MetadataRepository/CachedDoctrineMetadataRepository.php(156): OpenConext\\EngineBlock\\Metadata\\MetadataRepository\\CachedDoctrineMetadataRepository->invoke()\n#13 /apps/installation/OpenConext-engineblock/OpenConext-engineblock-6.11.0/library/EngineBlock/Corto/Module/Bindings.php(563): OpenConext\\EngineBlock\\Metadata\\MetadataRepository\\CachedDoctrineMetadataRepository->findIdentityProviderByEntityId()\n#14 /apps/installation/OpenConext-engineblock/OpenConext-engineblock-6.11.0/library/EngineBlock/Corto/Module/Bindings.php(331): EngineBlock_Corto_Module_Bindings->_verifyKnownIdP()\n#15 /apps/installation/OpenConext-engineblock/OpenConext-engineblock-6.11.0/library/EngineBlock/Corto/Module/Service/AssertionConsumer.php(88): EngineBlock_Corto_Module_Bindings->receiveResponse()\n#16 /apps/installation/OpenConext-engineblock/OpenConext-engineblock-6.11.0/library/EngineBlock/Corto/Module/Services.php(71): EngineBlock_Corto_Module_Service_AssertionConsumer->serve()\n#17 /apps/installation/OpenConext-engineblock/OpenConext-engineblock-6.11.0/library/EngineBlock/Corto/ProxyServer.php(375): EngineBlock_Corto_Module_Services->serve()\n#18 /apps/installation/OpenConext-engineblock/OpenConext-engineblock-6.11.0/library/EngineBlock/Corto/Adapter.php(341): EngineBlock_Corto_ProxyServer->serve()\n#19 /apps/installation/OpenConext-engineblock/OpenConext-engineblock-6.11.0/library/EngineBlock/Corto/Adapter.php(107): EngineBlock_Corto_Adapter->_callCortoServiceUri()\n#20 /apps/installation/OpenConext-engineblock/OpenConext-engineblock-6.11.0/src/OpenConext/EngineBlockBundle/Controller/ServiceProviderController.php(80): EngineBlock_Corto_Adapter->consumeAssertion()\n#21 /apps/installation/OpenConext-engineblock/OpenConext-engineblock-6.11.0/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(151): OpenConext\\EngineBlockBundle\\Controller\\ServiceProviderController->consumeAssertionAction()\n#22 /apps/installation/OpenConext-engineblock/OpenConext-engineblock-6.11.0/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(68): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw()\n#23 /apps/installation/OpenConext-engineblock/OpenConext-engineblock-6.11.0/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(200): Symfony\\Component\\HttpKernel\\HttpKernel->handle()\n#24 /apps/installation/OpenConext-engineblock/OpenConext-engineblock-6.11.0/web/app.php(17): Symfony\\Component\\HttpKernel\\Kernel->handle()\n#25 {main}","message_prefix":null}}
```

**Comment by baszoetekouw** [comment]
@johanib this might be related to the mdui issues we discussed this morning related to #1338

**Comment by thijskh** [comment]
Has been fixed #1264

**Comment by baszoetekouw** [comment]
to be tested
