### ISSUE TITLE
More friendly error message when fetching IdPs-metadata for non-existing SP

### ISSUE THREAD

**Issue by baszoetekouw** [OpenConext/OpenConext-engineblock#211]
When requesting IdPs-metadata for a non-existing SP, Engine currently returns "error an error occurred: It is not possible to sign in. Please try again."

```
curl -v 'https://engine.test.surfconext.nl/authentication/proxy/idps-metadata?sp-entity-id=urn:bestaat:niet'
[...]
> GET /authentication/proxy/idps-metadata?sp-entity-id=urn:bestaat:niet HTTP/1.1
> Host: engine.test.surfconext.nl
> User-Agent: curl/7.44.0
> Accept: */*
>
< HTTP/1.1 500 Internal Server Error
< Server: nginx/1.8.0
< Date: Tue, 10 Nov 2015 13:56:44 GMT
< Content-Type: text/html; charset=UTF-8
[...]
 <div class="mod-content">
    <h1>Error - An error occurred</h1>
    <p>
        It is not possible to sign in. Please try again.
    </p>
```

The logs show:

```
Nov 10 14:56:44 t03 EBLOG[31074]: [2015-11-10 14:56:44] engineblock.INFO: Handling incoming request: GET /authentication/proxy/idps-metadata {"request_id":"5641f79c53af1","session_id":null} []
Nov 10 14:56:44 t03 EBLOG[31074]: [2015-11-10 14:56:44] engineblock.INFO: Calling service 'idpsMetadataService' {"request_id":"5641f79c53af1","session_id":"KPrgY6VPRGotIZKCfNMO-W2,HFf"} []
Nov 10 14:56:44 t03 EBLOG[31074]: [2015-11-10 14:56:44] engineblock.ERROR: Unable to find 'urn:bestaat:niet' in any configured repository {"request_id":"5641f79c53af1","session_id":"KPrgY6VPRGotIZKCfNMO-W2,HFf"} {"exception":{"severity":"ERROR","location":"/var/opt/openconext/OpenConext-engineblock-feature-pep/library/EngineBlock/Dispatcher.php:79","userId":null,"idp":null,"sp":null,"details":"EngineBlock_Exception: Unable to find 'urn:bestaat:niet' in any configured repository\n#0 /var/opt/openconext/OpenConext-engineblock-feature-pep/library/EngineBlock/Dispatcher.php(48): EngineBlock_Dispatcher->_handleDispatchException(Object(OpenConext\\Component\\EngineBlockMetadata\\MetadataRepository\\EntityNotFoundException))\n#1 /var/opt/openconext/OpenConext-engineblock-feature-pep/www/authentication/index.php(13): EngineBlock_Dispatcher->dispatch()\n#2 {main}\n\nOpenConext\\Component\\EngineBlockMetadata\\MetadataRepository\\EntityNotFoundException: Unable to find 'urn:bestaat:niet' in any configured repository\n#0 /var/opt/openconext/OpenConext-engineblock-feature-pep/library/EngineBlock/Corto/Module/Service/IdpsMetadata.php(15): OpenConext\\Component\\EngineBlockMetadata\\MetadataRepository\\CompositeMetadataRepository->fetchServiceProviderByEntityId('urn:bestaat:nie...')\n#1 /var/opt/openconext/OpenConext-engineblock-feature-pep/library/EngineBlock/Corto/Module/Services.php(56): EngineBlock_Corto_Module_Service_IdpsMetadata->serve('idpsMetadataSer...')\n#2 /var/opt/openconext/OpenConext-engineblock-feature-pep/library/EngineBlock/Corto/ProxyServer.php(331): EngineBlock_Corto_Module_Services->serve('idpsMetadataSer...')\n#3 /var/opt/openconext/OpenConext-engineblock-feature-pep/library/EngineBlock/Corto/Adapter.php(342): EngineBlock_Corto_ProxyServer->serve('idpsMetadataSer...', '')\n#4 /var/opt/openconext/OpenConext-engineblock-feature-pep/library/EngineBlock/Corto/Adapter.php(112): EngineBlock_Corto_Adapter->_callCortoServiceUri('idpsMetadataSer...')\n#5 /var/opt/openconext/OpenConext-engineblock-feature-pep/appli
Nov 10 14:56:44 t03 EBLOG[31074]: [2015-11-10 14:56:44] engineblock.NOTICE: An error was caught {"request_id":"5641f79c53af1","session_id":"KPrgY6VPRGotIZKCfNMO-W2,HFf"} []
Nov 10 14:56:44 t03 EBLOG[31074]: [2015-11-10 14:56:44] engineblock.NOTICE: Showing feedback page with message: SURFconext - Error - An error occurred {"request_id":"5641f79c53af1","session_id":"KPrgY6VPRGotIZKCfNMO-W2,HFf"} []
```

A friendlier and more to the point error message would be appreciated here.

**Comment by thijskh** [comment]
This will be solved by removing this functionality from EB

**Comment by MKodde** [comment]
The resolution to this issue will land with the release of EngineBlock 6.1. Closing this issue.
