### ISSUE TITLE
Unknown-preselected-idp error not displayed correctly

### ISSUE THREAD

**Issue by thijskh** [OpenConext/OpenConext-engineblock#320]
In EB 5rc1, being sent to `https://engine.<…>/authentication/feedback/unknown-preselected-idp?idp-hash=example` results in "Error - An Error Occurred" instead of the correct error page with logging as per below.

Seems to be a simple capitalization issue in `src/OpenConext/EngineBlockBundle/Controller/FeedbackController.php` (`Idp` vs `IdP`).

```
Aug 16 15:31:47 t06 EBLOG[3246]: [2016-08-16 15:31:47] engineblock.INFO: Handling incoming request: GET /authentication/feedback/unknown-preselected-idp {"session_id":null,"request_id":"57b315c398daf"} []
Aug 16 15:31:47 t06 EBLOG[3246]: [2016-08-16 15:31:47] request.INFO: Matched route "authentication_feedback_unknown_preselected_idp". {"session_id":null,"request_id":"57b315c398daf"} {"route_parameters":{"_controller":"engineblock.controller.authentication.feedback:unknownPreselectedIdpAction","domain":"…","_route":"authentication_feedback_unknown_preselected_idp"},"request_uri":"https://engine.…/authentication/feedback/unknown-preselected-idp?idp-hash=aa"}
Aug 16 15:31:47 t06 EBLOG[3246]: [2016-08-16 15:31:47] security.INFO: Populated the TokenStorage with an anonymous Token. {"session_id":null,"request_id":"57b315c398daf"} []
Aug 16 15:31:47 t06 EBLOG[3246]: [2016-08-16 15:31:47] engineblock.ERROR: View script "Authentication/View/Feedback/UnknownPreselectedIdP.phtml" does not exist as a file itself and also not as a file at "/opt/openconext/OpenConext-engineblock-5.0.0-rc1/app/Resources/views/modules/Authentication/View/Feedback/UnknownPreselectedIdP.phtml" | Caught Unhandled EngineBlock_Exception {"session_id":"DjnWxg945sVbx1CAMoCwHAtBBKd","request_id":"57b315c398daf"} {"exception":{"severity":"ERROR","location":"/opt/openconext/OpenConext-engineblock-5.0.0-rc1/library/EngineBlock/View.php:27","userId":null,"idp":null,"sp":null,"details":"EngineBlock_Exception: View script \"Authentication/View/Feedback/UnknownPreselectedIdP.phtml\" does not exist as a file itself and also not as a file at \"/opt/openconext/OpenConext-engineblock-5.0.0-rc1/app/Resources/views/modules/Authentication/View/Feedback/UnknownPreselectedIdP.phtml\"\n#0 /opt/openconext/OpenConext-engineblock-5.0.0-rc1/src/OpenConext/EngineBlockBundle/Controller/FeedbackController.php(237): EngineBlock_View->render('Authentication/...')\n#1 [internal function]: OpenConext\\EngineBlockBundle\\Controller\\FeedbackController->unknownPreselectedIdpAction()\n#2 /opt/openconext/OpenConext-engineblock-5.0.0-rc1/app/bootstrap.php.cache(3109): call_user_func_array(Array, Array)\n#3 /opt/openconext/OpenConext-engineblock-5.0.0-rc1/app/bootstrap.php.cache(3071): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 1)\n#4 /opt/openconext/OpenConext-engineblock-5.0.0-rc1/app/bootstrap.php.cache(3222): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#5 /opt/openconext/OpenConext-engineblock-5.0.0-rc1/app/bootstrap.php.cache(2444): Symfony\\Component\\HttpKernel\\DependencyInjection\\ContainerAwareHttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#6 /opt/openconext/OpenConext-engineblock-5.0.0-rc1/web/app.php(22): Symfony\\Component\\HttpKernel\\Kernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#7 {main}","message_prefix":null}}
Aug 16 15:31:47 t06 EBLOG[3246]: [2016-08-16 15:31:47] engineblock.NOTICE: An error was caught {"session_id":"DjnWxg945sVbx1CAMoCwHAtBBKd","request_id":"57b315c398daf"} []
Aug 16 15:31:47 t06 EBLOG[3246]: [2016-08-16 15:31:47] engineblock.NOTICE: Showing feedback page with message: SURFconext - Error - An error occurred {"session_id":"DjnWxg945sVbx1CAMoCwHAtBBKd","request_id":"57b315c398daf"} []
```

**Comment by DRvanR** [comment]
Resolved through #323
